# Generated by Django 4.1.7 on 2023-07-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=100)),
                ('materials_provide', models.CharField(choices=[('credit_card', 'Credit_card'), ('debit_card', 'Debit_card')], max_length=100)),
            ],
        ),
    ]
